version: "3"

services:
  reserva-casino:
    build:
      context: .
      dockerfile: Dockerfile
    image: reserva-casino-image
    container_name: reserva-casino
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
